/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proto.h"

bool_t
xdr_type_nom (XDR *xdrs, type_nom *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNOM))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_nom (XDR *xdrs, liste_nom *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct cell_nom), (xdrproc_t) xdr_cell_nom))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cell_nom (XDR *xdrs, cell_nom *objp)
{
	register int32_t *buf;

	 if (!xdr_type_nom (xdrs, &objp->nom))
		 return FALSE;
	 if (!xdr_liste_nom (xdrs, &objp->suivant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ls_res (XDR *xdrs, ls_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->erreur))
		 return FALSE;
	switch (objp->erreur) {
	case 0:
		 if (!xdr_liste_nom (xdrs, &objp->ls_res_u.liste))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_type_bloc (XDR *xdrs, type_bloc *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXBLOC))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_bloc (XDR *xdrs, liste_bloc *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct cell_bloc), (xdrproc_t) xdr_cell_bloc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cell_bloc (XDR *xdrs, cell_bloc *objp)
{
	register int32_t *buf;

	 if (!xdr_type_bloc (xdrs, &objp->bloc))
		 return FALSE;
	 if (!xdr_liste_bloc (xdrs, &objp->suivant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_res (XDR *xdrs, read_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->erreur))
		 return FALSE;
	switch (objp->erreur) {
	case 0:
		 if (!xdr_liste_bloc (xdrs, &objp->read_res_u.fichier))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_write_parm (XDR *xdrs, write_parm *objp)
{
	register int32_t *buf;

	 if (!xdr_type_nom (xdrs, &objp->nom))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->ecraser))
		 return FALSE;
	 if (!xdr_liste_bloc (xdrs, &objp->donnees))
		 return FALSE;
	return TRUE;
}
